name: Build-Test-Publish Flow

on:
  push:
    branches: [ "master" ]

jobs:
  build_test:
    name: Build and Test 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build_docker_iamge:
    name: Build and Push Docker Image
    needs: build_test
    runs-on: ubuntu-latest
    permissions:
      packages: write  
    steps:
    - name: Set image name and postfix
      run: |
        echo "DOCKER_IMAGE_POSTFIX=$(date +%Y-%m-%d_%s)" >> "$GITHUB_ENV"
        echo "DOCKER_IMAGE_NAME=ghcr.io/rumkit/telegram-torrserver-bot" >> "$GITHUB_ENV"
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}"
        file: TTSBot/Dockerfile
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_POSTFIX }},${{ env.DOCKER_IMAGE_NAME }}:latest